GRANT USAGE ON SCHEMA sigit_new TO sigit_new_rw;


GRANT SELECT,UPDATE,INSERT,DELETE,TRUNCATE ON ALL TABLES IN SCHEMA sigit_new TO sigit_new_rw;

GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA sigit_new TO sigit_new_rw;

GRANT SELECT,UPDATE ON ALL SEQUENCES IN SCHEMA sigit_new TO sigit_new_rw;
